### ISSUE TITLE
Use github actions 

### ISSUE THREAD

**Issue by ry** [denoland/vscode_deno#1]
Here is the old travis.yml
```
sudo: false
language: node_js

env:
  global:
    - DENO_VERSION=v0.40.0
    - YARN_VERSION=1.19.2

node_js:
  - "12"

cache:
  directories:
    - "node_modules"
  yarn: true

before_install:
  - curl -L https://deno.land/x/install/install.sh | sh -s $DENO_VERSION
  - export PATH="$HOME/.deno/bin:$PATH"
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version $YARN_VERSION
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn global add vsce
  - yarn

script:
  - yarn run check
  - yarn compile
  - vsce package
```
